apiVersion: v1
kind: Service
metadata:
 name: backend-db
spec:
 selector:
   app: backend-db
 ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
 name: backend
spec:
 selector:
   app: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: ml-db
spec:
 selector:
   app: ml-db
 ports:
   - protocol: TCP
     port: 3306
     targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
 name: ml
spec:
 selector:
  app: ml
 ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
 name: frontend
spec:
 type: NodePort
 selector:
  app: frontend
 ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000